### ISSUE TITLE
Videos broken on advanced course

### ISSUE THREAD

**Issue by aaronbbrown** [mesosphere/open-docs#120]
The videos at https://open.mesosphere.com/advanced-course/ are throwing the error

```
NoSuchKeyThe specified key does not exist.Videos/Mesos-Intro-Lecture-12/media/index_player.html8308D70ACEF492DCnpLqRUQScOm2NWLD16Q/wQXvVEjM3uPKRWU+epvZkEGe6n8ezqsCgqfy0ETUKr6+IjUZ0IXjiw0=
```

As an example, the URL https://s3-us-west-2.amazonaws.com/docs-staging.mesosphere.com/Videos/Mesos-Intro-Lecture-12/media/index_player.html?embedIFrameId=embeddedSmartPlayerInstance is throwing a 404 from AWS.

This was working until about 10AM ET today.

**Comment by ssk2** [comment]
Aaron,  can you ask Joel to look at this please?

**Comment by aaronbbrown** [comment]
Who is Joel?

**Comment by joel-hamill** [comment]
@aaronbbrown That is me. I will fix. Thanks :)

**Comment by vmahedia** [comment]
they are broken from "4. starting marathon" section.

**Comment by ssk2** [comment]
@aaronbbrown Haha, sorry - I mistook you for a different Aaron who works for us :)

**Comment by ssk2** [comment]
@aaronbbrown, @vmahedia - thanks for reporting the problem, we've figured out the issue. It might be a few hours before the videos are live again (we need to re-upload them).

**Comment by vmahedia** [comment]
@ssk2 This is the best/ideal tutorial so far, every step worked like a charm without any surprises which is rare. Fantastic job, thanks. :+1:

**Comment by aaronbbrown** [comment]
+1 about quality of the tutorial.

**Comment by ssk2** [comment]
That's good feedback! All thanks to @zedshaw!

**Comment by ssk2** [comment]
These are back online now, thanks for your patience!
