### ISSUE TITLE
ImportError: No module named mesos

### ISSUE THREAD

**Issue by tegansnyder** [mesosphere/open-docs#161]
When I get to last step of [Exercise 3](https://open.mesosphere.com/advanced-course/using-apache-mesos/) and try to bring up the `mesos ps` I get a python import error.

```sh
[vagrant@node1 mesos]$ mesos ps --master=$MASTER
Traceback (most recent call last):
  File "/usr/bin/mesos-ps", line 10, in <module>
    from mesos import http
ImportError: No module named mesos
```

I have my path setup as follows:
```sh
# ~/.bash_profile
export PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7/site-packages/
```

Any ideas? It appears python is unaware of where to find the packages. Maybe I overlooked something?

**Comment by tegansnyder** [comment]
Update it appears running the following fixes:
```sh
# install pip on node1 then run:
sudo pip install mesos.cli
```

**Comment by ohisa** [comment]
I met the some issue, too.
I fixed it with pip from EPEL.

```
[vagrant@node1 ~]$ sudo yum install -y epel-release
[vagrant@node1 ~]$ sudo yum install -y python-pip
[vagrant@node1 ~]$ sudo pip install pip --upgrade
[vagrant@node1 ~]$ sudo pip install mesos.cli
[vagrant@node1 ~]$ mesos ps
```

"-- master=$MASTER" is not required for new mesos.cli.
