### ISSUE TITLE
Digitalocean links don't lead to Digitalocean content

### ISSUE THREAD

**Issue by gscott** [mesosphere/open-docs#66]
Ref: https://github.com/mesosphere/open-docs/blob/master/getting-started/cloud/digitalocean/mesosphere.md

References inside to digitalocean.mesosphere.com, but that redirects to the generic Community vs Enterprise page.

Docs reference the Launchpad but there is no Digitalocean content on the launchpad.

**Comment by ssk2** [comment]
Thanks @gscott  - we must have missed that page! `digitalocean.mesosphere.com` is no longer available and this page should have been removed.
