### ISSUE TITLE
Trouble building mesos-dns

### ISSUE THREAD

**Issue by matsluni** [mesosphere/open-docs#83]
Hi,

I am working my way through the tutorial and get stuck a bit at the point where I have to build mesos-dns [Building and running mesos-dns](https://open.mesosphere.com/advanced-course/building-and-running-mesos-dns/). For me it seems like the given command does not work:
```shell
make restoredeps build
```

The current build instructions for [mesos-dns](https://github.com/mesosphere/mesos-dns) show a different way how to build mesos-dns.
```shell
godep go build ./...
```

This worked also not for me.
For me the following command worked: 
```shell
godep go build 
```

What is the correct way to build mesos-dns for the tutorial?

Many Thanks for the great tutorial so far!
Matthias

**Comment by tsenart** [comment]
@matsluni: Thanks for reporting this documentation bug! I'll follow up with a fix.
